// Code generated by MockGen. DO NOT EDIT.
// Source: middleware.go
//
// Generated by this command:
//
//	mockgen -source=middleware.go -destination=middleware_mock_test.go -package=transaction
//

// Package transaction is a generated GoMock package.
package transaction

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockMiddleware is a mock of Middleware interface.
type MockMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareMockRecorder
	isgomock struct{}
}

// MockMiddlewareMockRecorder is the mock recorder for MockMiddleware.
type MockMiddlewareMockRecorder struct {
	mock *MockMiddleware
}

// NewMockMiddleware creates a new mock instance.
func NewMockMiddleware(ctrl *gomock.Controller) *MockMiddleware {
	mock := &MockMiddleware{ctrl: ctrl}
	mock.recorder = &MockMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddleware) EXPECT() *MockMiddlewareMockRecorder {
	return m.recorder
}

// MiddlewareValidateToken mocks base method.
func (m *MockMiddleware) MiddlewareValidateToken(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MiddlewareValidateToken", c)
}

// MiddlewareValidateToken indicates an expected call of MiddlewareValidateToken.
func (mr *MockMiddlewareMockRecorder) MiddlewareValidateToken(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MiddlewareValidateToken", reflect.TypeOf((*MockMiddleware)(nil).MiddlewareValidateToken), c)
}
